### ISSUE TITLE
Proposal To Do List

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/R2Py2#1]
- [X] setup project repository  
- [x] create and update README  
  - [x] team members  
- [x] collaboration strategy (document: CONTRIBUTING.md)  
- [x] code of conduct  (document: CONDUCT.md)  
- [x] identify survey question  
- [x] additional question to identify confounding variables  
  - [x] explanation for chosen questions  
- [x] plan of analysis  
- [x] discussion of aspects of "Ethics" document that are relevant to our survey

**Comment by mkeyim** [comment]
Survey question will be:

_Does the first programming language someone learns influence whether they prefer R or Python (or have no preference)?_

**Comment by mkeyim** [comment]
Ex:
- Which do you prefer: Python or R?
- What is the first computing language you learned?
- How many computing languages do you know?
- What was your undergraduate degree in?
- How long have you been coding?
- How long have you been coding in Python?
- How long have you been coding in R?
- Which language did you learn first, Python or R?
