### ISSUE TITLE
Fixing typos in the final md

### ISSUE THREAD

**Issue by phuntsoktseten** [UBC-MDS/R2Py2#27]
1.`Python and R are the two dominate Data Science programming languages, we set out  determine how people's`
--- add a to after out
2. We identified the following potential counfounding variables:
--- spell confounding correctly
3.However, none of these coefficents were found to be statisically significant at 5%, a potential reason for this 
-- spell coefficients and statistically correctly

**Comment by mkeyim** [comment]
Fixed! Thanks Phuntsok
