### ISSUE TITLE
suggestions for last merge

### ISSUE THREAD

**Issue by mani-kohli** [UBC-MDS/R2Py2#28]
1. The majority, 65% of respondents, preferred to use Python over R for a data analysis task 
suggestion ->
The **majority or respondents, 65%**, preferred to use Python over R for a data analysis task.

2. 2nd plot, angle x axis labels
edited suggested changes in bold -->
Those that learned a dev_lang (**either** C/C++/C#/Java/Javascript) seem to prefer python over R **most of the time**. The majority of the survey respondents were split between those that learned Python and web_dev_lang languages first. **This** heatmap was faceted with which **the** language **majority of** people believe have better documentation. **This** seems to **indicate** that more people prefer the language they believe **has** better documentation (**in this case, Python**).

3. 2nd heatmap, angle x axis labels
edited suggested changes in bold -->
**This plot seems to indicate that** those with a Business, Math/Statistics/ or Computer Science backgrounds **preferred** Python **while** those with Sciences/Other degrees **preferred** R over Python.

4. The size of the data set that people tend to work with for a data analysis task appears to have no influence on the language a person prefers.
edited suggested changes in bold -->
**The size of the data worked with** for a data analysis task appears to **show** no influence on the language a person prefers.

5. It seems highly correlated that people prefer to choose the language that they believe has better documentation. Over half of the respondents had experience with small analysis projects.
edited suggested changes in bold -->
**There seems to be a high correlation between** which programming language **people prefer to the language they** believe has better documentation. Over half of the respondents had experience with small analysis projects.

**Comment by mkeyim** [comment]
Added! Thanks Mani
