### ISSUE TITLE
Choosing variable questions

### ISSUE THREAD

**Issue by mkeyim** [UBC-MDS/R2Py2#7]
Please check off questions that we should ask

- [x]  Which do you prefer: Python or R?

- [x] What is the first computing language you learned?

- [ ]   How many computing languages do you know?

- [x] What was your undergraduate degree in?

- [ ] How long have you been coding?

- [ ] How long have you been coding in Python?

- [ ] How long have you been coding in R?

- [ ] Which language did you learn first, Python or R?

**Comment by mkeyim** [comment]
please post any other questions we can ask:

**Comment by mani-kohli** [comment]
- [ ] - Which language is more readable, Python or R?
- [ ] - Which language is easier to debug, Python or R?
- [x] - Which language did you find had the quickest learning curve, Python or R?
- [ ] - Which language do you find statistical analyses easier to implement, Python or R?
- [ ] - Which language do you find visualization tools easier to implement, Python or R?
- [ ] - Which language would you prefer to be an expert in, Python or R?

**Comment by phuntsoktseten** [comment]
- [ ] What is the confounding factor in our analysis?

**Comment by mkeyim** [comment]
- [x] Are your analysis projects typically small(10K rows), medium(10-1M Rows), big (1m+ rows) ?

**Comment by mkeyim** [comment]
- [x] Which language do you think has better documentation when it comes to Data Analysis?

**Comment by mkeyim** [comment]
Final variables have been chosen.
